openapi: 3.1.0
info:
  title: apidoc
  version: 0.1.0
paths:
  /users/register:
    post:
      tags:
        - Auth
      summary: Create User
      description: Регистрация
      operationId: create_user_users_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    default: Некорректные входные данные
                type: object
        '409':
          description: Пользователь с таким email уже существует
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    default: Объект с такими данными уже существует
                type: object
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Вход
      operationId: login_users_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/protected:
    get:
      tags:
        - Auth
      summary: Protected
      description: Контент только для зарегистрированных пользователей
      operationId: protected_users_protected_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '401':
          description: Неверный токен или истек срок действия
          content:
            application/json:
              example:
                detail: Invalid Token
components:
  schemas:
    ErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
        - detail
      title: ErrorResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RegisterResponse:
      properties:
        user:
          $ref: '#/components/schemas/UserRead'
        access_token:
          type: string
          title: Access Token
      type: object
      required:
        - user
        - access_token
      title: RegisterResponse
    UserCreate:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          minLength: 4
          title: Password
        first_name:
          type: string
          maxLength: 255
          title: First Name
        last_name:
          type: string
          maxLength: 255
          title: Last Name
      type: object
      required:
        - email
        - password
        - first_name
        - last_name
      title: UserCreate
    UserLogin:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
        - email
        - password
      title: UserLogin
    UserRead:
      properties:
        email:
          type: string
          format: email
          title: Email
        is_active:
          type: boolean
          title: Is Active
          default: true
        is_verified:
          type: boolean
          title: Is Verified
          default: false
        is_superuser:
          type: boolean
          title: Is Superuser
          default: false
        first_name:
          type: string
          maxLength: 255
          title: First Name
        last_name:
          type: string
          maxLength: 255
          title: Last Name
      type: object
      required:
        - email
        - first_name
        - last_name
      title: UserRead
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
