openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /users/register:
    post:
      tags:
        - Auth
      summary: Create User
      description: Регистрация
      operationId: create_user_users_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    default: Некорректные входные данные
                type: object
        '409':
          description: Пользователь с таким email уже существует
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    default: Объект с такими данными уже существует
                type: object
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Вход
      operationId: login_users_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/me:
    get:
      tags:
        - Auth
      summary: Whoami
      operationId: whoami_users_me_get
      responses:
        '200':
          description: Получить информацию о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserMeResponse'
        '401':
          description: Неверный токен или истек срок действия. Cделайте рефреш токена
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
                    default: Invalid Token
                type: object
  /users/refresh:
    get:
      tags:
        - Auth
      summary: Refresh Token
      description: Обновление access токена
      operationId: refresh_token_users_refresh_get
      parameters:
        - name: refresh_token
          in: cookie
          required: false
          schema:
            type: string
            title: Refresh Token
      responses:
        '200':
          description: Получить access-токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Срок действия refresh-токена истек. Войдите в систему заново
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Invalid Token
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/list:
    get:
      tags:
        - Auth
      summary: Get Users List
      description: Получение всех пользователей
      operationId: get_users_list_users_list_get
      parameters:
        - name: user_id
          in: query
          required: false
          schema:
            type: integer
            title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserRead'
                title: Response Get Users List Users List Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/{user_id}:
    get:
      tags:
        - Auth
      summary: Get Particular User
      description: Получение пользователя по id
      operationId: get_particular_user_users__user_id__get
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Пользователь не найден
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/update/{user_id}:
    patch:
      tags:
        - Auth
      summary: Update User
      description: Обновление пользователя по id
      operationId: update_user_users_update__user_id__patch
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Пользователь успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'
                type: object
                properties:
                  detail:
                    type: string
                    default: Пользователь обновлен
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Пользователь не найден
        '409':
          description: Пользователь с таким email уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Объект с такими данными уже существует
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/delete/{user_id}:
    delete:
      tags:
        - Auth
      summary: Delete User
      description: Удаление пользователя по id
      operationId: delete_user_users_delete__user_id__delete
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      responses:
        '204':
          description: Successful Response
        '403':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: У вас недостаточно прав
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Пользователь не найден
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
        - detail
      title: ErrorResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LoginResponse:
      properties:
        access_token:
          type: string
          title: Access Token
      type: object
      required:
        - access_token
      title: LoginResponse
    RegisterResponse:
      properties:
        user:
          $ref: '#/components/schemas/UserRead'
        access_token:
          type: string
          title: Access Token
      type: object
      required:
        - user
        - access_token
      title: RegisterResponse
    UserCreate:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          minLength: 4
          title: Password
        first_name:
          type: string
          maxLength: 255
          title: First Name
        last_name:
          type: string
          maxLength: 255
          title: Last Name
      type: object
      required:
        - email
        - password
        - first_name
        - last_name
      title: UserCreate
    UserLogin:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
        - email
        - password
      title: UserLogin
    UserMeResponse:
      properties:
        user:
          $ref: '#/components/schemas/UserRead'
      type: object
      required:
        - user
      title: UserMeResponse
    UserRead:
      properties:
        id:
          type: integer
          title: Id
        email:
          type: string
          format: email
          title: Email
        is_active:
          type: boolean
          title: Is Active
          default: true
        is_verified:
          type: boolean
          title: Is Verified
          default: false
        is_superuser:
          type: boolean
          title: Is Superuser
          default: false
        first_name:
          type: string
          maxLength: 255
          title: First Name
        last_name:
          type: string
          maxLength: 255
          title: Last Name
      type: object
      required:
        - id
        - email
        - first_name
        - last_name
      title: UserRead
    UserUpdate:
      properties:
        email:
          anyOf:
            - type: string
              format: email
            - type: 'null'
          title: Email
        first_name:
          type: string
          maxLength: 255
          title: First Name
        last_name:
          type: string
          maxLength: 255
          title: Last Name
      type: object
      required:
        - first_name
        - last_name
      title: UserUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
